export enum Colors {
  support = 'support',
  transparentGray = 'transparent-gray',
  transparent = 'transparent',
  transparentRed = 'transparent-red',
  green = 'green',
  red = 'red',
  orange = 'orange',
  yellow = 'yellow',
  gold = 'gold',
  blue = 'blue',
  chat = 'chat',
  lightBlue = 'light-blue',
  supported = 'supported',
  disable = 'disable',
  primary = 'primary',
  secondary = 'secondary',
  tertiary = 'tertiary',
  grayTransparent = 'gray-transparent',
  cyan = 'cyan'
}
