# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  pull-requests:
    "develop":
      - step:
          name: Check tests and syntax before pull request
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm test
            - npm run lint
