interface Country {
  name: string;
  code: string;
  id: string;
}
export const countries: Country[] = [
  { name: 'United States of America', code: 'US', id: '840' },
  { name: 'Canada', code: 'CA', id: '124' },
  { name: 'United Kingdom', code: 'GB', id: '826' },
  { name: 'Afghanistan', code: 'AF', id: '4' },
  { name: 'Aland Islands', code: 'AX', id: '248' },
  { name: 'Albania', code: 'AL', id: '8' },
  { name: 'Algeria', code: 'DZ', id: '12' },
  { name: 'American Samoa', code: 'AS', id: '16' },
  { name: 'Andorra', code: 'AD', id: '20' },
  { name: 'Angola', code: 'AO', id: '24' },
  { name: 'Anguilla', code: 'AI', id: '660' },
  { name: 'Antarctica', code: 'AQ', id: '10' },
  { name: 'Antigua and Barbuda', code: 'AG', id: '28' },
  { name: 'Argentina', code: 'AR', id: '32' },
  { name: 'Armenia', code: 'AM', id: '51' },
  { name: 'Aruba', code: 'AW', id: '533' },
  { name: 'Australia', code: 'AU', id: '36' },
  { name: 'Austria', code: 'AT', id: '40' },
  { name: 'Azerbaijan', code: 'AZ', id: '31' },
  { name: 'Bahamas', code: 'BS', id: '44' },
  { name: 'Bahrain', code: 'BH', id: '48' },
  { name: 'Bangladesh', code: 'BD', id: '50' },
  { name: 'Barbados', code: 'BB', id: '52' },
  { name: 'Belarus', code: 'BY', id: '112' },
  { name: 'Belgium', code: 'BE', id: '56' },
  { name: 'Belize', code: 'BZ', id: '84' },
  { name: 'Benin', code: 'BJ', id: '204' },
  { name: 'Bermuda', code: 'BM', id: '60' },
  { name: 'Bhutan', code: 'BT', id: '64' },
  { name: 'Bolivia', code: 'BO', id: '68' },
  { name: 'Bosnia and Herzegovina', code: 'BA', id: '70' },
  { name: 'Botswana', code: 'BW', id: '72' },
  { name: 'Bouvet Island', code: 'BV', id: '74' },
  { name: 'Brazil', code: 'BR', id: '76' },
  { name: 'British Virgin Islands', code: 'VG', id: '92' },
  { name: 'British Indian Ocean Territory', code: 'IO', id: '86' },
  { name: 'Brunei Darussalam', code: 'BN', id: '96' },
  { name: 'Bulgaria', code: 'BG', id: '100' },
  { name: 'Burkina Faso', code: 'BF', id: '854' },
  { name: 'Burundi', code: 'BI', id: '108' },
  { name: 'Cambodia', code: 'KH', id: '116' },
  { name: 'Cameroon', code: 'CM', id: '120' },
  { name: 'Cape Verde', code: 'CV', id: '132' },
  { name: 'Cayman Islands', code: 'KY', id: '136' },
  { name: 'Central African Republic', code: 'CF', id: '140' },
  { name: 'Chad', code: 'TD', id: '148' },
  { name: 'Chile', code: 'CL', id: '152' },
  { name: 'China', code: 'CN', id: '156' },
  { name: 'Hong Kong', code: 'HK', id: '344' },
  { name: 'Macao', code: 'MO', id: '446' },
  { name: 'Christmas Island', code: 'CX', id: '162' },
  { name: 'Cocos (Keeling) Islands', code: 'CC', id: '166' },
  { name: 'Colombia', code: 'CO', id: '170' },
  { name: 'Comoros', code: 'KM', id: '174' },
  { name: 'Congo', code: 'CG', id: '178' },
  { name: 'Cook Islands', code: 'CK', id: '184' },
  { name: 'Costa Rica', code: 'CR', id: '188' },
  { name: 'Côte d´Ivoire', code: 'CI', id: '384' },
  { name: 'Croatia', code: 'HR', id: '191' },
  { name: 'Cuba', code: 'CU', id: '192' },
  { name: 'Cyprus', code: 'CY', id: '196' },
  { name: 'Czech Republic', code: 'CZ', id: '203' },
  { name: 'Denmark', code: 'DK', id: '208' },
  { name: 'Djibouti', code: 'DJ', id: '262' },
  { name: 'Dominica', code: 'DM', id: '212' },
  { name: 'Dominican Republic', code: 'DO', id: '214' },
  { name: 'Ecuador', code: 'EC', id: '218' },
  { name: 'Egypt', code: 'EG', id: '818' },
  { name: 'El Salvador', code: 'SV', id: '222' },
  { name: 'Equatorial Guinea', code: 'GQ', id: '226' },
  { name: 'Eritrea', code: 'ER', id: '232' },
  { name: 'Estonia', code: 'EE', id: '233' },
  { name: 'Ethiopia', code: 'ET', id: '231' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK', id: '238' },
  { name: 'Faroe Islands', code: 'FO', id: '234' },
  { name: 'Fiji', code: 'FJ', id: '242' },
  { name: 'Finland', code: 'FI', id: '246' },
  { name: 'France', code: 'FR', id: '250' },
  { name: 'French Guiana', code: 'GF', id: '254' },
  { name: 'French Polynesia', code: 'PF', id: '258' },
  { name: 'French Southern Territories', code: 'TF', id: '260' },
  { name: 'Gabon', code: 'GA', id: '266' },
  { name: 'Gambia', code: 'GM', id: '270' },
  { name: 'Georgia', code: 'GE', id: '268' },
  { name: 'Germany', code: 'DE', id: '276' },
  { name: 'Ghana', code: 'GH', id: '288' },
  { name: 'Gibraltar', code: 'GI', id: '292' },
  { name: 'Greece', code: 'GR', id: '300' },
  { name: 'Greenland', code: 'GL', id: '304' },
  { name: 'Grenada', code: 'GD', id: '308' },
  { name: 'Guadeloupe', code: 'GP', id: '312' },
  { name: 'Guam', code: 'GU', id: '316' },
  { name: 'Guatemala', code: 'GT', id: '320' },
  { name: 'Guernsey', code: 'GG', id: '831' },
  { name: 'Guinea', code: 'GN', id: '324' },
  { name: 'Guinea-Bissau', code: 'GW', id: '624' },
  { name: 'Guyana', code: 'GY', id: '328' },
  { name: 'Haiti', code: 'HT', id: '332' },
  { name: 'Heard and Mcdonald Islands', code: 'HM', id: '334' },
  { name: 'Vatican', code: 'VA', id: '336' },
  { name: 'Honduras', code: 'HN', id: '340' },
  { name: 'Hungary', code: 'HU', id: '348' },
  { name: 'Iceland', code: 'IS', id: '352' },
  { name: 'India', code: 'IN', id: '356' },
  { name: 'Indonesia', code: 'ID', id: '360' },
  { name: 'Iran', code: 'IR', id: '364' },
  { name: 'Iraq', code: 'IQ', id: '368' },
  { name: 'Ireland', code: 'IE', id: '372' },
  { name: 'Isle of Man', code: 'IM', id: '833' },
  { name: 'Israel', code: 'IL', id: '376' },
  { name: 'Italy', code: 'IT', id: '380' },
  { name: 'Jamaica', code: 'JM', id: '388' },
  { name: 'Japan', code: 'JP', id: '392' },
  { name: 'Jersey', code: 'JE', id: '832' },
  { name: 'Jordan', code: 'JO', id: '400' },
  { name: 'Kazakhstan', code: 'KZ', id: '398' },
  { name: 'Kenya', code: 'KE', id: '404' },
  { name: 'Kiribati', code: 'KI', id: '296' },
  { name: 'Korea (North)', code: 'KP', id: '408' },
  { name: 'Korea (South)', code: 'KR', id: '410' },
  { name: 'Kuwait', code: 'KW', id: '414' },
  { name: 'Kyrgyzstan', code: 'KG', id: '417' },
  { name: 'Lao PDR', code: 'LA', id: '418' },
  { name: 'Latvia', code: 'LV', id: '428' },
  { name: 'Lebanon', code: 'LB', id: '422' },
  { name: 'Lesotho', code: 'LS', id: '426' },
  { name: 'Liberia', code: 'LR', id: '430' },
  { name: 'Libya', code: 'LY', id: '434' },
  { name: 'Liechtenstein', code: 'LI', id: '438' },
  { name: 'Lithuania', code: 'LT', id: '440' },
  { name: 'Luxembourg', code: 'LU', id: '442' },
  { name: 'Macedonia', code: 'MK', id: '807' },
  { name: 'Madagascar', code: 'MG', id: '450' },
  { name: 'Malawi', code: 'MW', id: '454' },
  { name: 'Malaysia', code: 'MY', id: '458' },
  { name: 'Maldives', code: 'MV', id: '462' },
  { name: 'Mali', code: 'ML', id: '466' },
  { name: 'Malta', code: 'MT', id: '470' },
  { name: 'Marshall Islands', code: 'MH', id: '584' },
  { name: 'Martinique', code: 'MQ', id: '474' },
  { name: 'Mauritania', code: 'MR', id: '478' },
  { name: 'Mauritius', code: 'MU', id: '480' },
  { name: 'Mayotte', code: 'YT', id: '175' },
  { name: 'Mexico', code: 'MX', id: '484' },
  { name: 'Micronesia', code: 'FM', id: '583' },
  { name: 'Moldova', code: 'MD', id: '498' },
  { name: 'Monaco', code: 'MC', id: '492' },
  { name: 'Mongolia', code: 'MN', id: '496' },
  { name: 'Montenegro', code: 'ME', id: '499' },
  { name: 'Montserrat', code: 'MS', id: '500' },
  { name: 'Morocco', code: 'MA', id: '504' },
  { name: 'Mozambique', code: 'MZ', id: '508' },
  { name: 'Myanmar', code: 'MM', id: '104' },
  { name: 'Namibia', code: 'NA', id: '516' },
  { name: 'Nauru', code: 'NR', id: '520' },
  { name: 'Nepal', code: 'NP', id: '524' },
  { name: 'Netherlands', code: 'NL', id: '528' },
  { name: 'Netherlands Antilles', code: 'AN', id: '530' },
  { name: 'New Caledonia', code: 'NC', id: '540' },
  { name: 'New Zealand', code: 'NZ', id: '554' },
  { name: 'Nicaragua', code: 'NI', id: '558' },
  { name: 'Niger', code: 'NE', id: '562' },
  { name: 'Nigeria', code: 'NG', id: '566' },
  { name: 'Niue', code: 'NU', id: '570' },
  { name: 'Norfolk Island', code: 'NF', id: '574' },
  { name: 'Northern Mariana Islands', code: 'MP', id: '580' },
  { name: 'Norway', code: 'NO', id: '578' },
  { name: 'Oman', code: 'OM', id: '512' },
  { name: 'Pakistan', code: 'PK', id: '586' },
  { name: 'Palau', code: 'PW', id: '585' },
  { name: 'Palestinian Territory', code: 'PS', id: '275' },
  { name: 'Panama', code: 'PA', id: '591' },
  { name: 'Papua New Guinea', code: 'PG', id: '598' },
  { name: 'Paraguay', code: 'PY', id: '600' },
  { name: 'Peru', code: 'PE', id: '604' },
  { name: 'Philippines', code: 'PH', id: '608' },
  { name: 'Pitcairn', code: 'PN', id: '612' },
  { name: 'Poland', code: 'PL', id: '616' },
  { name: 'Portugal', code: 'PT', id: '620' },
  { name: 'Puerto Rico', code: 'PR', id: '630' },
  { name: 'Qatar', code: 'QA', id: '634' },
  { name: 'Réunion', code: 'RE', id: '638' },
  { name: 'Romania', code: 'RO', id: '642' },
  { name: 'Russian Federation', code: 'RU', id: '643' },
  { name: 'Rwanda', code: 'RW', id: '646' },
  { name: 'Saint-Barthélemy', code: 'BL', id: '652' },
  { name: 'Saint Helena', code: 'SH', id: '654' },
  { name: 'Saint Kitts and Nevis', code: 'KN', id: '659' },
  { name: 'Saint Lucia', code: 'LC', id: '662' },
  { name: 'Saint-Martin (French part)', code: 'MF', id: '663' },
  { name: 'Saint Pierre and Miquelon', code: 'PM', id: '666' },
  { name: 'Saint Vincent and Grenadines', code: 'VC', id: '670' },
  { name: 'Samoa', code: 'WS', id: '882' },
  { name: 'San Marino', code: 'SM', id: '674' },
  { name: 'Sao Tome and Principe', code: 'ST', id: '678' },
  { name: 'Saudi Arabia', code: 'SA', id: '682' },
  { name: 'Senegal', code: 'SN', id: '686' },
  { name: 'Serbia', code: 'RS', id: '688' },
  { name: 'Seychelles', code: 'SC', id: '690' },
  { name: 'Sierra Leone', code: 'SL', id: '694' },
  { name: 'Singapore', code: 'SG', id: '702' },
  { name: 'Slovakia', code: 'SK', id: '703' },
  { name: 'Slovenia', code: 'SI', id: '705' },
  { name: 'Solomon Islands', code: 'SB', id: '90' },
  { name: 'Somalia', code: 'SO', id: '706' },
  { name: 'South Africa', code: 'ZA', id: '710' },
  { name: 'South Georgia and the SSI', code: 'GS', id: '239' },
  { name: 'South Sudan', code: 'SS', id: '728' },
  { name: 'Spain', code: 'ES', id: '724' },
  { name: 'Sri Lanka', code: 'LK', id: '144' },
  { name: 'Sudan', code: 'SD', id: '736' },
  { name: 'Suriname', code: 'SR', id: '740' },
  { name: 'Svalbard and Jan Mayen Islands', code: 'SJ', id: '744' },
  { name: 'Swaziland', code: 'SZ', id: '748' },
  { name: 'Sweden', code: 'SE', id: '752' },
  { name: 'Switzerland', code: 'CH', id: '756' },
  { name: 'Syrian Arab Republic (Syria)', code: 'SY', id: '760' },
  { name: 'Taiwan', code: 'TW', id: '158' },
  { name: 'Tajikistan', code: 'TJ', id: '762' },
  { name: 'Tanzania', code: 'TZ', id: '834' },
  { name: 'Thailand', code: 'TH', id: '764' },
  { name: 'Timor-Leste', code: 'TL', id: '626' },
  { name: 'Togo', code: 'TG', id: '768' },
  { name: 'Tokelau', code: 'TK', id: '772' },
  { name: 'Tonga', code: 'TO', id: '776' },
  { name: 'Trinidad and Tobago', code: 'TT', id: '780' },
  { name: 'Tunisia', code: 'TN', id: '788' },
  { name: 'Turkey', code: 'TR', id: '792' },
  { name: 'Turkmenistan', code: 'TM', id: '795' },
  { name: 'Turks and Caicos Islands', code: 'TC', id: '796' },
  { name: 'Tuvalu', code: 'TV', id: '798' },
  { name: 'Uganda', code: 'UG', id: '800' },
  { name: 'Ukraine', code: 'UA', id: '804' },
  { name: 'United Arab Emirates', code: 'AE', id: '784' },
  { name: 'US Minor Outlying Islands', code: 'UM', id: '581' },
  { name: 'Uruguay', code: 'UY', id: '858' },
  { name: 'Uzbekistan', code: 'UZ', id: '860' },
  { name: 'Vanuatu', code: 'VU', id: '548' },
  { name: 'Venezuela', code: 'VE', id: '862' },
  { name: 'Viet Nam', code: 'VN', id: '704' },
  { name: 'Virgin Islands, US', code: 'VI', id: '850' },
  { name: 'Wallis and Futuna Islands', code: 'WF', id: '876' },
  { name: 'Western Sahara', code: 'EH', id: '732' },
  { name: 'Yemen', code: 'YE', id: '887' },
  { name: 'Zambia', code: 'ZM', id: '894' },
  { name: 'Zimbabwe', code: 'ZW', id: '716' }
];
