export enum DashboardActionType {
  GET_BY_DASH_ARTIST_API = 'GET_BY_DASH_ARTIST_API',
  GET_BY_DASH_ARTIST_API_FAILURE = 'GET_BY_DASH_ARTIST_API_FAILURE',
  GET_BY_DASH_ARTIST_API_SUCCESS = 'GET_BY_DASH_ARTIST_API_SUCCESS',
  UPDATE_PROPERTY = 'UPDATE_PROPERTY',
  UPDATE_SET_INITIAL_PROPERTY = 'UPDATE_SET_INITIAL_PROPERTY'
}
