export enum NavbarActionType {
  TOGGLE_NAVBAR_TWOACTIONS = 'TOGGLE_NAVBAR_TWOACTIONS',
  UPDATE_NAVBAR_TWOACTIONS = 'UPDATE_NAVBAR_TWOACTIONS',
  UPDATE_NAVBAR_PROPERTY = 'UPDATE_NAVBAR_PROPERTY',
  }
  