export enum SettingsActionType {
  UPDATE_PROPERTY = 'UPDATE_PROPERTY',
  UPDATE_MODAL = 'UPDATE_MODAL',
  UPDATE_POPUP_MODAL = 'UPDATE_POPUP_MODAL',
  SHOW_TOAST = 'SHOW_TOAST',
  HIDE_TOAST = 'HIDE_TOAST'
}
