export enum FriendActionType {
  GET_FRIENDS_ALL_API = 'GET_FRIENDS_ALL_API',
  GET_FRIENDS_ALL_API_FAILURE = 'GET_FRIENDS_ALL_API_FAILURE',
  GET_FRIENDS_ALL_API_SUCCESS = 'GET_FRIENDS_ALL_API_SUCCESS',
  GET_FRIEND_BY_ID_API = 'GET_FRIEND_BY_ID_API',
  GET_FRIEND_BY_ID_API_SUCCESS = 'GET_FRIEND_BY_ID_API_SUCCESS',
  GET_FRIEND_BY_ID_API_FAILURE = 'GET_FRIEND_BY_ID_API_FAILURE'
}
