export enum FriendActionType {
  GET_ALL_API = 'GET_ALL_API',
  GET_ALL_API_FAILURE = 'GET_ALL_API_FAILURE',
  GET_ALL_API_SUCCESS = 'GET_ALL_API_SUCCESS',
  GET_BY_ID_API = 'GET_BY_ID_API',
  GET_BY_ID_API_SUCCESS = 'GET_BY_ID_API_SUCCESS',
  GET_BY_ID_API_FAILURE = 'GET_BY_ID_API_FAILURE'
}
